---
name: Build packages
on:
  - workflow_dispatch


jobs:
  build-wheel:
    runs-on: macOS
    steps:
      - name: Checkout repos
        uses: actions/checkout@v1
      - run: |
              export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
              export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
              export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
              python setup.py bdist_wheel
