---
name: Build packages
on:
  - workflow_dispatch


jobs:
  build-wheel:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repos
        uses: actions/checkout@v1
      - run: python setup.py bdist_wheel
