---
name: Build packages
on:
  - workflow_dispatch


jobs:
  build-wheel:
    runs-on: macOS
    steps:
      - name: Checkout repos
        uses: actions/checkout@v1
      - run: PATH="/opt/homebrew/opt/libpq/bin:$PATH" python setup.py bdist_wheel
