---
name: M1 wheel build 
on:
  - workflow_dispatch


jobs:
  build-wheel:
    runs-on: macOS
    steps:
      - name: Checkout repos
        uses: actions/checkout@v1
      - run: |
              export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
              export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
              export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
              arch -arm64e python setup.py bdist_wheel
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "psycopg2-m1"
          path: dist/*.whl
