---
name: M1 wheel build 
on:
  - workflow_dispatch


jobs:
  build-wheel:
    strategy:
      matrix:
        version: ["3.7.12", "3.8.12", "3.9.9", "3.10.1"]
    runs-on: macOS
    steps:
      - name: Checkout repos
        uses: actions/checkout@v1
      - run: |
              export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
              export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
              export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
              pyenv global {{ matrix.version }}
              arch -arm64e python setup.py bdist_wheel
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "psycopg2-m1-py{{ matrix.version }}"
          path: dist/*.whl
